### ISSUE TITLE
Error with some AlphaFold proteins

### ISSUE THREAD

**Issue by bdezonia** [weberdak/traj2nmr#1]
We are using traj2nmr in some scripts we have written. We found a problem when running traj2nmr on an AlphaFold protein.

The error manifests itself in our code as a missing KeyCode 'B'. In mdtraj a 'B' implies the protein has a residue in isolated beta-bridge.

We can fix the problem if we add this at the end of the CONVERT dictionary definition in utils.py:

'ASX': 'B', 'B': 'ASX',

This was an apparent mapping needed by inspecting mdtraj source. You can search for 'B' in the mdtraj source code to see what I mean here.

I tried to open a pull request for this but was denied access.

Let me know if you have any questions. Thanks.

**Comment by weberdak** [comment]
Hi Barry,

I have just added you as a collaborator, and have opened a branch for this issue. Hopefully this allows you to make the pull request. The branch can be cloned by:

git fetch origin
git checkout 1-error-with-some-alphafold-proteins

Nice to see this repo getting some use.

Cheers,
Daniel

**Comment by bdezonia** [comment]
Thanks. Things are working. I made the PR. I forgot to reference there that it closes this ticket. Please close this ticket when you merge that PR.

It turns out I forgot to fork your repo. That is why I could not push the PR. Your instructions worked though. Thanks.

**Comment by weberdak** [comment]
All good now, thanks for the fix.
